name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Homebrew 🍺
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git 🖥
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Pull bottles from PR 🍾
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: brew pr-pull --debug --tap=${GITHUB_REPOSITORY} ${PULL_REQUEST}

      - name: Push commits to master 📤
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: master

      - name: Delete branch 🗑
        if: github.event.pull_request.head.repo.fork == false
        run: git push --delete origin ${BRANCH}
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
